virtualgovservices/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('landingpage', views.landingpage, name='landingpage'),
    path('', views.main, name='main'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('anträge/', views.übersicht_anträge, name='übersicht_anträge'),
    path('antrag_annehmen/<int:verfahren_id>/', views.antrag_annehmen, name='antrag_annehmen'),
    path('verfahren_delegieren/<int:verfahren_id>/', views.verfahren_delegieren, name='verfahren_delegieren'),
    path('bescheid_erstellen/<int:verfahren_id>/', views.bescheid_erstellen, name='bescheid_erstellen'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('meine_antraege/', views.meine_antraege, name='meine_antraege'),
    path('settings/', views.profile_settings, name='settings'),
    # path('settings_beamte/', views.profile_settings_beamte, name='settings_beamte'),
    path('hundeanmeldung/', views.hundeanmeldung, name='hundeanmeldung'),
    path('wohnsitzanmeldung/', views.wohnsitzanmeldung, name='wohnsitzanmeldung'),
    path('dokumente/<uuid:uuid>/', views.dokument_detail_view, name='dokument_detail'),
    path('statistik/', views.statistik, name='statistik'),
    # APIs
    path('api/verfahrensdauer/', views.verfahrensdauer_abfrage),
    path('api/antragstellung/', views.antragstellung),
    path('api/akt_historie/<int:verfahren_id>/', views.akt_historie_abfrage),
]

virtualgovservices/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import uuid
from .functions import generate_qr_code
from django.core.files.base import ContentFile
from django.utils import timezone


class Beamter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    profileimg = models.ImageField(upload_to = 'virtualgovservices/profile_images/', default = '/virtualgovservices/profile_images/avatar.jpg')
    anrede = models.CharField(max_length=10, null=True)
    vorname = models.CharField(max_length=100, null=True)
    nachname = models.CharField(max_length=100, null=True)
    raum = models.CharField(max_length=20, null=True)
    telefonnummer = models.CharField(max_length=20, null=True)
    email = models.EmailField(blank=True, null=True)
    zuständigkeit = models.CharField(max_length=100, null=True)
    nr_zuständigkeit = models.CharField(max_length=100, null=True)

    ROLE_CHOICES = (
        ('beamter', 'Beamter'),
    )
    rolle = models.CharField(max_length=10, choices=ROLE_CHOICES, default='beamter')

    def __str__(self):
        return f"{self.anrede} {self.vorname} {self.nachname}"


class Verfahren(models.Model):
    # Die fortlaufende Nummer wird automatisch als Primärschlüssel zugewiesen
    nummer = models.AutoField(primary_key=True)
    antragssteller = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    erstellt_am = models.DateTimeField(auto_now_add=True)
    aktualisiert_am = models.DateTimeField(auto_now=True)
    zustand = models.CharField(max_length=100, default="Antrag gestellt")
    # Ein ForeignKey, der das Verfahren einem Beamten zuordnet
    verantwortlicher = models.ForeignKey(Beamter, on_delete=models.CASCADE, null=True)
    # verantwortlicher = models.TextField(default="Beamter X")
    themengebiet = models.CharField(max_length=100)

    def __str__(self):
        return f"Verfahren {self.nummer} - {self.themengebiet}"


class Buerger(models.Model):
    # OneToOneField erstellt eine Eins-zu-Eins-Beziehung mit dem User-Modell
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profileimg = models.ImageField(upload_to = 'virtualgovservices/profile_images/', default = '/virtualgovservices/profile_images/avatar.jpg')
    anrede = models.CharField(max_length=10)
    vorname = models.CharField(max_length=100)
    nachname = models.CharField(max_length=100)
    strasse = models.CharField(max_length=100)
    postleitzahl = models.CharField(max_length=10) 
    ort = models.CharField(max_length=100)
    telefonnummer = models.CharField(max_length=20)
    email = models.EmailField(blank=True)
    geburtsdatum = models.DateField(blank=True, default="1995-01-01")
    
    ROLE_CHOICES = (
        ('buerger', 'Bürger'),
    )
    rolle = models.CharField(max_length=10, choices=ROLE_CHOICES, default='buerger')

    def __str__(self):
        return f"{self.anrede} {self.vorname} {self.nachname}"


class Dokument(models.Model):
    # Die URI ist eindeutig für jedes Dokument
    uri = models.TextField(unique=True)
    url = models.URLField(blank=True)
    # Jedes Dokument ist einem Verfahren zugeordnet
    verfahren = models.ForeignKey(Verfahren, on_delete=models.CASCADE)
    erstellt_am = models.DateTimeField(auto_now_add=True)
    # digitale_signatur = models.TextField(blank=True)  # Placeholder Signatur
    inhalt = models.TextField(blank=True, null=True)
    titel = models.CharField(max_length=200, blank=True, null=True)
    bemerkungen = models.TextField(blank=True, null=True)

    # Wenn das Dokument neu ist und noch keine URI hat, generieren wir eine
    def save(self, *args, **kwargs):
        if not self.uri:
            self.uri = uuid.uuid4()
            self.url = ("https://193.196.52.181/virtualgovservices/dokumente/" + str(self.uri) + "/")
            
        super(Dokument, self).save(*args, **kwargs)

    def __str__(self):
        return f"Dokument für Verfahren {self.verfahren.nummer}"


class Hundeanmeldung(models.Model):
    # Ein ForeignKey, der den Antrag dem Bürger zuordnet
    buerger = models.ForeignKey(Buerger, related_name='hundeanmeldungen', on_delete=models.CASCADE)
    angemeldet_am = models.DateTimeField(auto_now_add=True)
    verfahren = models.OneToOneField(Verfahren, on_delete=models.CASCADE, null=True, blank=True)
    geschlecht_hund = models.CharField(max_length=100, null=True)
    name_hund = models.CharField(max_length=100, null=True)
    wurftag_hund = models.DateField(blank=True, null=True)
    rasse_hund = models.CharField(max_length=100, null=True)
    kampfhund = models.CharField(max_length=100, null=True)
    beginn_haltung_hund = models.DateField(blank=True, null=True)
    dokument = models.OneToOneField(Dokument, on_delete=models.CASCADE, null=True)

    def save(self, *args, **kwargs):
        if self.verfahren is None or not self.verfahren.nummer:
            # Wenn noch kein Verfahren zugeordnet ist, erstellen wir eines
            beamter = Beamter.objects.get(zuständigkeit="Hundesteuer")
            verfahren = Verfahren(
                antragssteller=self.buerger.user,
                verantwortlicher=beamter,
                themengebiet="Hundesteuer: Hundeanmeldung",
                aktualisiert_am=timezone.now()
            )
            verfahren.save()

            # Anschließend verknüpfen wir das Verfahren mit der Anmeldung
            self.verfahren = verfahren

            # und erstellen das dazugehörige Dokument
            dokument = Dokument.objects.create(
                verfahren=self.verfahren,
                inhalt=f"Antragszusammenfassung - Hundeanmeldung von {self.buerger.vorname} {self.buerger.nachname}",
            )

            if not self.dokument:
                self.dokument = dokument

        # Schließlich speichern wir die Anmeldung
        super(Hundeanmeldung, self).save(*args, **kwargs)

    def __str__(self):
        return f"Anmeldung von {self.buerger.vorname} {self.buerger.nachname} am {self.angemeldet_am.strftime('%d.%m.%Y')}"

class Wohnsitzanmeldung(models.Model):
    buerger = models.ForeignKey(Buerger, on_delete=models.CASCADE)
    angemeldet_am = models.DateTimeField(auto_now_add=True)
    verfahren = models.OneToOneField(Verfahren, on_delete=models.CASCADE, null=True, blank=True)
    dokument = models.OneToOneField(Dokument, on_delete=models.CASCADE, null=True)
    umzugsdatum = models.DateField()
    neue_strasse = models.CharField(max_length=100)
    neue_postleitzahl = models.CharField(max_length=10)
    neuer_ort = models.CharField(max_length=100)
    vorherige_adresse = models.CharField(max_length=100, blank=True)

    def save(self, *args, **kwargs):
        if self.verfahren is None or not self.verfahren.nummer:
            # Wenn noch kein Verfahren zugeordnet ist, erstellen wir eines
            beamter = Beamter.objects.get(zuständigkeit="Wohnsitz")
            verfahren = Verfahren(
                antragssteller=self.buerger.user,
                verantwortlicher=beamter,
                themengebiet="Wohnsitz: Wohnsitzanmeldung",
                aktualisiert_am=timezone.now()
            )
            verfahren.save()

            # Anschließend verknüpfen wir das Verfahren mit der Anmeldung
            self.verfahren = verfahren

            # und erstellen das dazugehörige Dokument
            dokument = Dokument.objects.create(
                verfahren=self.verfahren,
                inhalt=f"Antragszusammenfassung - Wohnsitzanmeldung von {self.buerger.vorname} {self.buerger.nachname}",
            )

            if not self.dokument:
                self.dokument = dokument

        # Schließlich speichern wir die Anmeldung
        super(Wohnsitzanmeldung, self).save(*args, **kwargs)

    def __str__(self):
        return f"Wohnsitzanmeldung von {self.buerger.vorname} {self.buerger.nachname} am {self.angemeldet_am.strftime('%d.%m.%Y')}"
        

virtualgovservices/forms.py
from django import forms
from .models import Buerger, Hundeanmeldung, Wohnsitzanmeldung, Beamter
from django.forms.widgets import DateInput

class BuergerDatenForm(forms.ModelForm):
    class Meta:
        model = Buerger
        fields = ['anrede', 'vorname', 'nachname', 'strasse', 'postleitzahl', 'ort', 'telefonnummer', 'email', 'geburtsdatum']
        labels = {
            'anrede': 'Anrede',
            'vorname': 'Vorname',
            'nachname': 'Nachname',
            'strasse': 'Strasse',
            'postleitzahl': 'Postleitzahl',
            'ort': 'Wohnort',
            'telefonnummer': 'Telefonnummer',
            'email': 'Email',
            'geburtsdatum': 'Geburtsdatum'
        }
        widgets = {
            'geburtsdatum': forms.DateInput(attrs={'type': 'date'}),
        }

class HundeanmeldungForm(forms.ModelForm):
    class Meta:
        model = Hundeanmeldung
        fields = ['name_hund', 'rasse_hund', 'geschlecht_hund', 'kampfhund', 'wurftag_hund', 'beginn_haltung_hund']
        labels = {
            'name_hund': 'Name',
            'rasse_hund': 'Rasse',
            'geschlecht_hund': 'Geschlecht',
            'kampfhund': 'Kampfhund?',
            'Wurftag_hund': 'Wurftag',
            'beginn_haltung_hund': 'Der Hund wird von mir gehalten seit dem'
        }
        widgets = {
            'geschlecht_hund': forms.RadioSelect(choices=[('männlich', 'Männlich'), ('weiblich', 'Weiblich')]),
            'kampfhund': forms.RadioSelect(choices=[('Ja', 'Ja'), ('Nein', 'Nein')]),
            'wurftag_hund': forms.DateInput(attrs={'type': 'date'}),
            'beginn_haltung_hund': forms.DateInput(attrs={'type': 'date'}),
        }

class WohnsitzanmeldungForm(forms.ModelForm):
    class Meta:
        model = Wohnsitzanmeldung
        fields = ['umzugsdatum', 'neue_strasse', 'neue_postleitzahl', 'neuer_ort', 'vorherige_adresse']
        labels = {
            'umzugsdatum': 'Einzugsdatum',
            'neue_strasse': 'Strasse',
            'neue_postleitzahl': 'Postleitzahl',
            'neuer_ort': 'Ort',
            'vorherige_adresse': 'Bisherige Anschrift',
        }
        widgets = {
            'umzugsdatum': forms.DateInput(attrs={'type': 'date'}),
        }

# class DelegierenForm(forms.Form):
#     neuer_verantwortlicher = forms.ModelChoiceField(
#         queryset=Beamter.objects.all(),
#         label="Neuen Verantwortlichen auswählen",
#         help_text="Wählen Sie einen Beamten aus, an den dieser Antrag delegiert werden soll."
#     )

class BescheidForm(forms.Form):
    titel = forms.CharField(label='Titel', max_length=200)
    inhalt = forms.CharField(label='Inhalt', widget=forms.Textarea)
    bemerkungen = forms.CharField(label='Bemerkungen', widget=forms.Textarea, required=False)

templates/virtualgovservices/base_antrag.html
{% load static %}
<!DOCTYPE html>
<html lang="de">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Antragsdokument</title>
    <script src="https://cdn.jsdelivr.net/npm/qrcodejs@1/qrcode.min.js"></script>
    <style type="text/css"> 
        @media screen {
            /* body {
                font-family: Arial, sans-serif;
                font-size: 12pt;
                background: #b9b9b9;
                color: #000;
            } */

            /* Stil für die DIN A4-Seite */
            .a4-page {
                width: 210mm;
                min-height: 297mm;
                margin: auto;
                padding: 20mm;
                border: 1px solid #D3D3D3;
                background: white;
                box-shadow: 0 0 5mm rgba(0, 0, 0, 0.1);
                box-sizing: border-box;
            }

            /* Stil für die Überschriften und Absätze */
            .a4-page h2 {
                font-family: Arial, sans-serif;
                color: #333;
                text-decoration: underline;
            }

            .a4-page p {
                font-family: Arial, sans-serif;
                color: #333;
            }

            /* Stil für die Abschnitte */
            .section {
                margin-bottom: 20px;
            }

            /* Stil für die Daten-Container */
            .data-container {
                background: #f9f9f9;
                padding: 10px;
                border: 1px solid #e0e0e0;
                border-radius: 5px;
            }

            /* Stil für einzelne Datenpunkte */
            .data-item {
                margin-bottom: 10px;
                font-family: Arial, sans-serif;
                color: #333;
                display: grid;
                grid-template-columns: 30% 70%;
                border-bottom: solid 1px rgb(189, 189, 189);
            }

            /* Stil für die Labels der Daten */
            .data-label {
                font-weight: bold;
            }

            /* Stil für QR-Code */
            .qr-code-img {
                max-width: 100px;
                height: auto;
            }
            /* Flexbox container */
            .flexbox {
                display: flex;
                align-items: center;
                justify-content: space-between;
                margin-bottom: 20px;
            }

            /* Left section */
            .left {
                flex-grow: 1;
            }

            /* Right section for QR Code */
            .right {
                flex-shrink: 0; /* Prevents the right section from shrinking */
                padding-left: 20px; /* Adds some space between left and right sections */
            }

        }

        @media print {
            .a4-page {
                width: 210mm;
                min-height: 297mm;
                margin: 0;
                padding: 20mm;
                box-shadow: none;
            }
        }
    </style>
</head>

<body>
    <div class="a4-page">
        <div class="flexbox">
            <div class="left">
                <h2>Antragszusammenfassung zum Antrag - {{ antrag.verfahren.themengebiet }}</h2>
                <p>Antrag von {{antrag.buerger.anrede}} {{ antrag.buerger.vorname }} {{antrag.buerger.nachname }}, eingegangen am {{ antrag.angemeldet_am|date:"d.m.Y" }}</p>
            </div>
            <div class="right">
                <div id="qrCode"></div>
                <script>
                    var currentPageUrl = window.location.href;
                    new QRCode(document.getElementById("qrCode"), {
                        text: currentPageUrl,
                        width: 128,
                        height: 128,
                        colorDark: "#000000",
                        colorLight: "#ffffff",
                        correctLevel: QRCode.CorrectLevel.H
                    });
                </script>
            </div>
        </div>

        <!-- Bürgerdaten -->
        <div class="section">
            <h2>Persönliche Daten des Bürgers</h2>
            <div class="data-container">
                <div class="data-item">
                    <span class="data-label">Name:</span> {{ antrag.buerger.anrede }} 
                    {{ antrag.buerger.vorname }}
                    {{ antrag.buerger.nachname }}
                </div>
                <div class="data-item">
                    <span class="data-label">Adresse:</span> {{ antrag.buerger.strasse }},
                    {{ antrag.buerger.postleitzahl }}
                    {{ antrag.buerger.ort }}
                </div>
                <div class="data-item">
                    <span class="data-label">Telefonnummer:</span> {{ antrag.buerger.telefonnummer }}
                </div>
                <div class="data-item">
                    <span class="data-label">E-Mail:</span> {{ antrag.buerger.email }}
                </div>
                <div class="data-item">
                    <span class="data-label">Geburtsdatum:</span> {{ antrag.buerger.geburtsdatum|date:"d.m.Y" }}
                </div>
            </div>
        </div>

        <!-- antragsdaten -->
        <div class="section">
            <h2>{{ header2 }}</h2>
            <div class="data-container">
            {% for label, value in antrag_data.items %}
                <div class="data-item">
                    <span class="data-label">{{ label }}:</span> {{ value }}
                </div>
            {% endfor %}
            </div>
        </div>

        <!-- Beamten-Daten -->
        <div class="section">
            <h2>Angaben zum Bearbeiter</h2>
            <div class="data-container">
                <div class="data-item">
                    <span class="data-label">Name:</span> {{ antrag.verfahren.verantwortlicher }}
                </div>
                <div class="data-item">
                    <span class="data-label">Telefonnummer:</span> {{ antrag.verfahren.verantwortlicher.telefonnummer }}
                </div>
                <div class="data-item">
                    <span class="data-label">E-Mail:</span> {{ antrag.verfahren.verantwortlicher.email }}
                </div>
                <div class="data-item">
                    <span class="data-label">Sachgebiet:</span> {{ antrag.verfahren.verantwortlicher.zuständigkeit }}
                </div>
            </div>
        </div>
        {% if signed_xml_str %}
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                // Button zum Umschalten der Anzeige
                var toggleButton = document.getElementById("toggleButton");
        
                // Textarea-Element
                var signaturTextarea = document.getElementById("signatur");
        
                // Event-Listener für den Klick auf den Button
                toggleButton.addEventListener("click", function() {
                    // Umschalten der Anzeige des Textarea
                    if (signaturTextarea.style.display === "none") {
                        signaturTextarea.style.display = "block";
                    } else {
                        signaturTextarea.style.display = "none";
                    }
                });
            });
        </script>
        <div class="section">
            <h2>Signatur:</h2>
            <button id="toggleButton">Signiert durch eGov</button>
            <textarea readonly style="display: none;" id="signatur">{{ signed_xml_str|safe }}</textarea>
        </div>
        {% endif %}

        
    </div>

</body>

</html>

templates/virtualgovservices/beamte_antragsuebersicht.html
{% extends "virtualgovservices/base.html" %}
{% block title %}eGov - Startseite{% endblock %}
{% block header %}{% endblock %}
{% block activeHome %}class='active'{% endblock %}
{% block bürger %}{% endblock %}
{% block main %}
{% load static %}
<div id="offen">
  <div class="main-section">Anträge zur Bearbeitung</div>
  {% for verfahren in verfahren_liste %}
  {% if verfahren.zustand != "abgeschlossen" %}
  <div class="main-section" id="v{{ verfahren.nummer }}">
    <h2>Verfahren {{ verfahren.themengebiet }}</h2>
    <p>vom {{ verfahren.erstellt_am }}</p>
    <h3>Verfahrens-ID: {{ verfahren.nummer }}</h3>
    <h3>Status: {{ verfahren.zustand }}, aktualisiert am {{ verfahren.aktualisiert_am }}</h3>
    <hr>
    <div class="data-container">
      <h4 class="underline">Antragssteller:</h4>
      <h3 style="color: black;">{{ verfahren.buerger_anrede }} {{ verfahren.buerger_vorname }} {{ verfahren.buerger_nachname }}</h3>
      <h3 style="color: black;">Tel.: {{ verfahren.buerger_telefonnummer }}</h3>
      <h3 style="color: black;">E-Mail: {{ verfahren.buerger_email }}</h3>
    </div>
    <h4 class="underline">Dokumente:</h4>
    <ul>
      {% for dokument in verfahren.dokument_set.all %}
      <li><a href="{{ dokument.url }}">{{ dokument.inhalt }}</a></li>
      {% endfor %}
    </ul>
    <div class="actions">
      <h4 class="underline">Aktionen:</h4>
      {% if verfahren.zustand != "Antrag angenommen" %}
      <form action="{% url 'antrag_annehmen' verfahren.nummer %}" method="post">
        {% csrf_token %}
        <button type="submit">Antrag annehmen</button>
      </form>
      {% endif %}
      <h4 class="underline">Antrag Delegieren</h4>
      <form action="{% url 'verfahren_delegieren' verfahren.nummer %}" method="post">
        {% csrf_token %}
        <label for="neuer_verantwortlicher">Neuen Verantwortlichen auswählen</label>
        <select name="neuer_verantwortlicher" id="neuer_verantwortlicher" required>
          {% for beamter in beamten_liste %}
          <option value="{{ beamter.id }}">{{ beamter.anrede }} {{ beamter.vorname }} {{ beamter.nachname }}</option>
          {% endfor %}
        </select>
        <button type="submit">Delegieren</button>
      </form>
      {% if verfahren.zustand == "Antrag angenommen" %}
      <h4 class="underline">Bescheid erstellen:</h4>
      <form action="{% url 'bescheid_erstellen' verfahren.nummer %}" method="post">
        {% csrf_token %}
        {{ bescheid_form.as_p }}
        <button type="submit">Bescheid erstellen</button>
      </form>
      {% endif %}
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div id="abgeschlossen">
  <div class="main-section">Abgeschlossene Anträge</div>
  {% for verfahren in verfahren_liste %}
  {% if verfahren.zustand == "abgeschlossen" %}
  <div class="main-section" id="v{{ verfahren.nummer }}">
    <h2>Verfahren {{ verfahren.themengebiet }}</h2>
    <p>vom {{ verfahren.erstellt_am }}</p>
    <h3>Verfahrens-ID: {{ verfahren.nummer }}</h3>
    <h3>Status: {{ verfahren.zustand }}, aktualisiert am {{ verfahren.aktualisiert_am }}</h3>
    <hr>
    <div class="data-container">
      <h4 class="underline">Antragssteller:</h4>
      <h3 style="color: black;">{{ verfahren.buerger_anrede }} {{ verfahren.buerger_vorname }} {{ verfahren.buerger_nachname }}</h3>
      <h3 style="color: black;">Tel.: {{ verfahren.buerger_telefonnummer }}</h3>
      <h3 style="color: black;">E-Mail: {{ verfahren.buerger_email }}</h3>
    </div>
    <h4 class="underline">Dokumente:</h4>
    <ul>
      {% for dokument in verfahren.dokument_set.all %}
      <li><a href="{{ dokument.url }}">{{ dokument.inhalt }}</a></li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}
  {% endfor %}
</div>
{% endblock %}
{% block loginxsignup %}{% endblock %}
{% block footer %}
<footer class="footer">
  <p>&copy; 2023 VirtualGov Services. Alle Rechte vorbehalten.</p>
  <div class="flexbox">
    <a href="#" {% block activeKontakt %}{% endblock %}>Kontakt</a>
    <a href="#" {% block activeFAQ %}{% endblock %}>FAQ</a>
    <a href="/impressum">Impressum</a>
    <a href="/datenschutz">Datenschutzerklärung</a>
  </div>
</footer>
{% endblock %}

templates/virtualgovservices/meine_antraege.html
{% extends "virtualgovservices/base.html" %}
{% block title %}eGov - Meine Anträge{% endblock %}
{% block header %}{% endblock %}
{% block activeMeineAnträge %}class='active'{% endblock %}
{% block loginxsignup %}{% endblock %}
{% block beamter %}{% endblock %}
{% block main %}
{% load static %}

{% for verfahren in verfahren_liste %}
<div class="main-section" id="v{{ verfahren.nummer }}">
    <h2>Verfahren {{ verfahren.themengebiet }}</h2>
    <p>vom {{ verfahren.erstellt_am }}</p>
    <h3>Verfahrens-ID: {{ verfahren.nummer }}</h3>
    <h3>Status: {{ verfahren.zustand }}, aktualisiert am {{ verfahren.aktualisiert_am }}</h3>
    <hr>
    <div class="data-container">
        <h4 class="underline">Sachbearbeiter:</h4>
        <h3 style="color: black;">{{ verfahren.verantwortlicher.anrede }} {{ verfahren.verantwortlicher.vorname }} {{ verfahren.verantwortlicher.nachname }} </h3>
        <h3 style="color: black;">Tel.: {{ verfahren.verantwortlicher.telefonnummer }}</h3>
        <h3 style="color: black;">E-Mail: 
            <a href="mailto:{{ verfahren.verantwortlicher.email }}?subject=Anfrage%20zu%20Verfahren-ID%20{{ verfahren.nummer }}&body=Antragssteller:%20{{ loggedin_user.anrede }}%20{{ loggedin_user.vorname }}%20{{ loggedin_user.nachname }}%0D%0ATelefonnummer:%20{{ loggedin_user.telefonnummer }}%0D%0AE-Mail:%20{{ loggedin_user.email }}%0D%0A%0D%0ASehr%20geehrte(r)%20{{ verfahren.verantwortlicher.anrede }}%20{{ verfahren.verantwortlicher.nachname }},%0D%0A%0D%0A">
            {{ verfahren.verantwortlicher.email }}
        </a></h3>
    </div>
    <h4 class="underline">Dokumente:</h4>
    <ul>
        {% for dokument in verfahren.dokument_set.all %}
        <li><a href="{{ dokument.url }}">{{ dokument.inhalt }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endfor %}
{% endblock %}